# Generated by Django 4.0.4 on 2022-05-02 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('professor_name', models.CharField(max_length=200)),
                ('number_of_credits', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=245)),
                ('location', models.CharField(blank=True, max_length=245)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avaible_seats', models.CharField(blank=True, max_length=100)),
                ('open', models.BooleanField(default=True)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
