# Generated by Django 4.0.3 on 2022-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
