# Generated by Django 4.0.3 on 2022-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_end_date_alter_classes_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AlterField(
            model_name='classes',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
