# Generated by Django 4.0.3 on 2022-05-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_studentprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
    ]
