# Generated by Django 4.0.3 on 2022-05-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_classes_class_name_alter_classes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='id',
            new_name='class_id',
        ),
    ]
